export class RCAIndex{
    public rgt_company: String
    public rgt_representative_name: String
    public rgt_dni: String
    public ret_representative_name: String
    public ret_dni: String
    public ret_phone: String
    public position: String
    public company_name: String
    public company_tax: String
    public social_security: String
    public contracted_by: String
    public address: String
    public city: String
    public country: String
    public phone: String
    public activities_calssification: String
    public insurance_company: String
    public preventive_resource_name_1: String
    public preventive_resource_dni_1: String
    public preventive_resource_name_2: String
    public preventive_resource_dni_2: String
    public wind_farm_name: String
    public wf_owner: String
    public pss_version: String
    public location_wind_farm: String
    public medical_service: String
    public phone_medical_service: String
    public nearest_medical_service: String
    public description_works: String
    public start_date_work: Date
    public work_completion_date: Date
    public worker_name: String
    public worker_dni: String
    public worker_position: String
    public rst_representative_name: String
    public rst_dni: String
    public rst_subcontractor_representatitve: String
    public rst_company_name_subcontracter: String
    public rst_ta: String
    public rst_city: String
    public rst_address: String
    public rst_description_work: String
                                       
}